name: LabsRun

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  fifth_lab_first_task: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - name: Cmake configure
        working-directory: fifth_lab/first
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ./
        
      - name: Cmake build
        shell: bash
        working-directory: fifth_lab/first
        run: cmake --build . --target lab_fifth -- -j 6
      
      - name: Run an app
        shell: bash
        working-directory: fifth_lab/first
        run: ./lab_fifth
  fifth_lab_second_task: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - name: Cmake configure
        working-directory: fifth_lab/second
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ./
        
      - name: Cmake build
        shell: bash
        working-directory: fifth_lab/second
        run: cmake --build . --target lab_fifth_second -- -j 6
      
      - name: Run an app
        shell: bash
        working-directory: fifth_lab/second
        run: ./lab_fifth_second
    
  fifth_lab_third_task: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - name: Cmake configure
        working-directory: fifth_lab/third
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ./
        
      - name: Cmake build
        shell: bash
        working-directory: fifth_lab/third
        run: cmake --build . --target lab_fifth_third -- -j 6
      
      - name: Run an app
        shell: bash
        working-directory: fifth_lab/third
        run: ./lab_fifth_third
